/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/tools/qrcode/promptpay/': RouteRecordInfo<'/tools/qrcode/promptpay/', '/tools/qrcode/promptpay', Record<never, never>, Record<never, never>>,
    '/tools/qrcode/promptpay/barcode': RouteRecordInfo<'/tools/qrcode/promptpay/barcode', '/tools/qrcode/promptpay/barcode', Record<never, never>, Record<never, never>>,
    '/tools/qrcode/promptpay/billing': RouteRecordInfo<'/tools/qrcode/promptpay/billing', '/tools/qrcode/promptpay/billing', Record<never, never>, Record<never, never>>,
    '/tools/qrcode/truemoney/': RouteRecordInfo<'/tools/qrcode/truemoney/', '/tools/qrcode/truemoney', Record<never, never>, Record<never, never>>,
    '/tools/validator/payment/promptpay': RouteRecordInfo<'/tools/validator/payment/promptpay', '/tools/validator/payment/promptpay', Record<never, never>, Record<never, never>>,
  }
}
